name: Upload to Local Server

on:
  push:
    paths:
      - '**/*'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          rm ssh_key.pem  # Remove the existing key file
          ssh-keygen -t rsa -b 4096 -m PEM -f ssh_key.pem
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          eval "$(ssh-agent -s)"
          ssh-add ssh_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload modified file to local server
        run: scp -i ssh_key.pem $(git diff --name-only ${{ github.sha }}^1 ${{ github.sha }}) suriya@192.168.137.1:/192.168.137.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Replace "username" with your local server's username
          # Replace "your-local-server-ip" with the IP address of your local server
          # Replace "/path/on/local/server" with the path on your local server where you want to copy the modified file
